/**
 * Centralized list of South African job titles used throughout the application.
 * This list is used for:
 * - Individual job seeker profiles
 * - Recruiter job postings
 * - Business job postings
 * - ATS candidate screening
 */

export const JOB_TITLES = [
  "Accountant",
  "Accountant (Government)",
  "Accounts Assistant",
  "Accounts Clerk",
  "Accounts Manager",
  "Accounts Payable Clerk",
  "Accounts Receivable Clerk",
  "Actuary",
  "Admin Assistant",
  "Admin Clerk",
  "Administrative Clerk",
  "Administrative Officer",
  "Administrator",
  "Advertising Executive",
  "Agricultural Advisor",
  "Agricultural Consultant",
  "Agricultural Engineer",
  "Agricultural Labourer",
  "Agronomist",
  "Analyst",
  "Animal Health Technician",
  "Application Developer",
  "Appraiser",
  "Architect",
  "Architect (Public Sector)",
  "Art Director",
  "Artisan (Carpenter)",
  "Artisan (Electrician)",
  "Artisan (Plumber)",
  "Assistant Accountant",
  "Assistant Director",
  "Assistant Manager",
  "Assistant Project Manager",
  "Associate Consultant",
  "Attorney",
  "Auditor",
  "Auto Electrician",
  "Automotive Mechanic",
  "Auxiliary Nurse",
  "Baker",
  "Bank Manager",
  "Barista",
  "Bartender",
  "Beautician",
  "Bookkeeper",
  "Brand Manager",
  "Broker",
  "Budget Analyst",
  "Building Inspector",
  "Business Analyst",
  "Business Consultant",
  "Business Development Executive",
  "Business Development Manager",
  "Business Manager",
  "Buyer",
  "Call Centre Agent",
  "Call Centre Manager",
  "Carpenter",
  "Cashier",
  "Chef",
  "Chemical Engineer",
  "Chief Director",
  "Chief Education Specialist",
  "Chief Financial Officer (Government)",
  "Chief Policy Analyst",
  "Civil Engineer",
  "Civil Engineer (Government)",
  "Cleaner",
  "Clerk",
  "Client Relationship Manager",
  "Client Services Manager",
  "Clinical Associate",
  "Clinical Psychologist",
  "Clothing Designer",
  "Coach",
  "Communications Officer",
  "Community Development Worker",
  "Community Health Worker",
  "Complaints Investigator",
  "Compliance Officer",
  "Computer Technician",
  "Conservation Officer",
  "Construction Manager",
  "Consultant",
  "Content Creator",
  "Contract Manager",
  "Controller",
  "Cook",
  "Copywriter",
  "Correctional Officer",
  "Cost Accountant",
  "Cost Engineer",
  "Costing Clerk",
  "Counsellor",
  "Court Interpreter",
  "Court Messenger",
  "Court Orderly",
  "Court Registrar",
  "Credit Controller",
  "Curriculum Advisor",
  "Customer Care Agent",
  "Customer Relations Officer",
  "Customer Service Agent",
  "Customer Service Manager",
  "Data Analyst",
  "Data Capturer",
  "Data Capturer (Government)",
  "Data Engineer",
  "Data Scientist",
  "Debt Collector",
  "Debtors Clerk",
  "Delivery Driver",
  "Dental Assistant",
  "Dental Therapist",
  "Dentist",
  "Deputy Director",
  "Deputy Director: Finance",
  "Designer",
  "Detective",
  "Diesel Mechanic",
  "Dietitian",
  "Digital Marketing Assistant",
  "Digital Marketing Manager",
  "Director",
  "Director-General",
  "Dispatch Clerk",
  "Distribution Manager",
  "Doctor",
  "Driver",
  "Early Childhood Educator",
  "Ecommerce Manager",
  "Editor",
  "Education Development Officer",
  "Education Specialist",
  "Educator (Primary)",
  "Educator (Secondary)",
  "Electrical Engineer",
  "Electrical Engineer (Government)",
  "Electrician",
  "Embedded Systems Engineer",
  "Engineer",
  "Environmental Consultant",
  "Environmental Health Officer",
  "Environmental Health Practitioner",
  "Environmental Manager",
  "Estimator",
  "Event Coordinator",
  "Event Manager",
  "Examination Officer",
  "Executive Assistant",
  "Executive Chef",
  "Executive Secretary",
  "Extension Officer",
  "Facilities Manager",
  "Fashion Designer",
  "Finance Administrator",
  "Finance Assistant",
  "Finance Manager",
  "Financial Advisor",
  "Financial Analyst",
  "Financial Clerk",
  "Financial Controller",
  "Fleet Manager",
  "Forensic Analyst",
  "Forestry Technician",
  "Forklift Operator",
  "Front Desk Assistant",
  "Front Desk Manager",
  "Front-End Developer",
  "Full Stack Developer",
  "Fund Accountant",
  "GIS Specialist",
  "General Labourer",
  "General Manager",
  "Geologist",
  "Graphic Designer",
  "HR Administrator",
  "HR Assistant",
  "HR Consultant",
  "HR Coordinator",
  "HR Manager",
  "Hair Stylist",
  "Handyman",
  "Head Chef",
  "Head of Department (HOD)",
  "Health & Safety Officer",
  "Healthcare Assistant",
  "Helpdesk Agent",
  "Human Resources Officer",
  "ICT Manager",
  "IT Administrator",
  "IT Consultant",
  "IT Coordinator",
  "IT Manager",
  "IT Support Technician",
  "IT Technician (Government)",
  "Immigration Officer",
  "Industrial Designer",
  "Industrial Engineer",
  "Information Officer",
  "Information Security Analyst",
  "Insurance Broker",
  "Insurance Consultant",
  "Interior Designer",
  "Intern",
  "Internal Auditor",
  "Investment Analyst",
  "Journalist",
  "Judge’s Secretary",
  "Junior Accountant",
  "Junior Administrator",
  "Junior Analyst",
  "Junior Architect",
  "Junior Developer",
  "Junior Engineer",
  "Junior Graphic Designer",
  "Laboratory Assistant",
  "Laboratory Technician",
  "Labour Relations Officer",
  "Landscape Architect",
  "Lawyer",
  "Lecturer",
  "Legal Advisor",
  "Legal Assistant",
  "Legal Clerk",
  "Legal Officer",
  "Librarian",
  "Life Coach",
  "Logistics Administrator",
  "Logistics Assistant",
  "Logistics Coordinator",
  "Logistics Manager",
  "Machine Operator",
  "Maintenance Assistant",
  "Maintenance Foreman",
  "Maintenance Manager",
  "Makeup Artist",
  "Manager",
  "Manufacturing Engineer",
  "Marine Biologist",
  "Market Research Analyst",
  "Marketing Assistant",
  "Marketing Consultant",
  "Marketing Coordinator",
  "Marketing Executive",
  "Marketing Manager",
  "Mason",
  "Mechanic",
  "Mechanical Engineer",
  "Medical Administrator",
  "Medical Officer",
  "Medical Receptionist",
  "Medical Representative",
  "Merchandiser",
  "Messenger",
  "Mining Engineer",
  "Mobile App Developer",
  "Nature Reserve Manager",
  "Network Administrator",
  "Network Administrator (Government)",
  "Network Engineer",
  "Nurse",
  "Nutritionist",
  "Occupational Therapist",
  "Office Administrator",
  "Office Assistant",
  "Operations Assistant",
  "Operations Coordinator",
  "Operations Manager",
  "Painter",
  "Paralegal",
  "Paramedic",
  "Payroll Administrator",
  "Payroll Clerk",
  "Personal Assistant",
  "Pharmacist",
  "Pharmacy Assistant",
  "Photographer",
  "Physical Therapist",
  "Physiotherapist",
  "Plumber",
  "Police Constable",
  "Police Officer",
  "Police Sergeant",
  "Policy Analyst",
  "Policy Researcher",
  "Portfolio Manager",
  "Post Office Clerk",
  "Power Plant Operator",
  "Principal",
  "Prison Warder",
  "Procurement Manager",
  "Procurement Officer",
  "Procurement Specialist",
  "Product Designer",
  "Product Manager",
  "Production Manager",
  "Programme Coordinator",
  "Programmer",
  "Project Administrator",
  "Project Coordinator",
  "Project Engineer",
  "Project Manager",
  "Project Manager (Public Works)",
  "Project Officer",
  "Property Manager",
  "Prosecutor",
  "Public Administration Officer",
  "Quality Assurance Analyst",
  "Quality Assurance Inspector",
  "Quality Assurance Manager",
  "Quantity Surveyor",
  "Quantity Surveyor (Government)",
  "Receptionist",
  "Recruiter",
  "Regional Manager",
  "Relationship Manager",
  "Research Analyst",
  "Research Assistant",
  "Restaurant Manager",
  "Retail Assistant",
  "Retail Manager",
  "Revenue Officer",
  "Roads Superintendent",
  "Rural Development Coordinator",
  "Safety Officer",
  "Sales Administrator",
  "Sales Assistant",
  "Sales Consultant",
  "Sales Executive",
  "Sales Manager",
  "Sales Representative",
  "School Administrator",
  "School Teacher",
  "Scientist",
  "Scrum Master",
  "Secretary",
  "Security Guard",
  "Security Officer",
  "Senior Accountant",
  "Senior Analyst",
  "Senior Clerk",
  "Senior Developer",
  "Senior Engineer",
  "Senior Manager",
  "Senior Project Manager",
  "Service Advisor",
  "Site Manager",
  "Social Media Manager",
  "Social Worker",
  "Software Developer",
  "Software Engineer",
  "Software Tester",
  "Solution Architect",
  "Sound Engineer",
  "State Attorney",
  "Store Assistant",
  "Store Manager",
  "Strategic Planner",
  "Student Intern",
  "Supervisor",
  "Supply Chain Analyst",
  "Supply Chain Clerk",
  "Supply Chain Manager",
  "Supply Chain Specialist",
  "Support Engineer",
  "Systems Administrator",
  "Systems Analyst",
  "Systems Developer (Government)",
  "Tailor",
  "Teacher",
  "Teaching Assistant",
  "Technical Assistant",
  "Technical Consultant",
  "Technical Support Engineer",
  "Technician",
  "Telemarketer",
  "Tour Guide",
  "Town Planner",
  "Traffic Officer",
  "Trainer",
  "Training Coordinator",
  "Training Facilitator",
  "Transport Manager",
  "Treasury Analyst",
  "Truck Driver",
  "Tutor",
  "Typist",
  "UX Designer",
  "Video Editor",
  "Waiter",
  "Warehouse Assistant",
  "Warehouse Manager",
  "Web Designer",
  "Web Developer",
  "Webmaster",
  "Welder",
  "Other",
] as const;

export type JobTitle = typeof JOB_TITLES[number];
